export interface CodigoTelefonoPais {
  pais: string;
  codigo: string;
}

export const CODIGO_TELEFONO_DEFECTO = '+591';

export const CODIGOS_TELEFONO_POR_PAIS: CodigoTelefonoPais[] = [
  { pais: 'Bolivia', codigo: '+591' },
  { pais: 'Afganistan', codigo: '+93' },
  { pais: 'Albania', codigo: '+355' },
  { pais: 'Alemania', codigo: '+49' },
  { pais: 'Andorra', codigo: '+376' },
  { pais: 'Angola', codigo: '+244' },
  { pais: 'Antigua y Barbuda', codigo: '+1268' },
  { pais: 'Arabia Saudita', codigo: '+966' },
  { pais: 'Argelia', codigo: '+213' },
  { pais: 'Argentina', codigo: '+54' },
  { pais: 'Armenia', codigo: '+374' },
  { pais: 'Australia', codigo: '+61' },
  { pais: 'Austria', codigo: '+43' },
  { pais: 'Azerbaiyan', codigo: '+994' },
  { pais: 'Bahamas', codigo: '+1242' },
  { pais: 'Banglades', codigo: '+880' },
  { pais: 'Barbados', codigo: '+1246' },
  { pais: 'Barein', codigo: '+973' },
  { pais: 'Belgica', codigo: '+32' },
  { pais: 'Belice', codigo: '+501' },
  { pais: 'Benin', codigo: '+229' },
  { pais: 'Bielorrusia', codigo: '+375' },
  { pais: 'Birmania', codigo: '+95' },
  { pais: 'Bosnia y Herzegovina', codigo: '+387' },
  { pais: 'Botsuana', codigo: '+267' },
  { pais: 'Brasil', codigo: '+55' },
  { pais: 'Brunei', codigo: '+673' },
  { pais: 'Bulgaria', codigo: '+359' },
  { pais: 'Burkina Faso', codigo: '+226' },
  { pais: 'Burundi', codigo: '+257' },
  { pais: 'Butan', codigo: '+975' },
  { pais: 'Cabo Verde', codigo: '+238' },
  { pais: 'Camboya', codigo: '+855' },
  { pais: 'Camerun', codigo: '+237' },
  { pais: 'Canada', codigo: '+1' },
  { pais: 'Catar', codigo: '+974' },
  { pais: 'Chad', codigo: '+235' },
  { pais: 'Chile', codigo: '+56' },
  { pais: 'China', codigo: '+86' },
  { pais: 'Chipre', codigo: '+357' },
  { pais: 'Colombia', codigo: '+57' },
  { pais: 'Comoras', codigo: '+269' },
  { pais: 'Corea del Norte', codigo: '+850' },
  { pais: 'Corea del Sur', codigo: '+82' },
  { pais: 'Costa de Marfil', codigo: '+225' },
  { pais: 'Costa Rica', codigo: '+506' },
  { pais: 'Croacia', codigo: '+385' },
  { pais: 'Cuba', codigo: '+53' },
  { pais: 'Dinamarca', codigo: '+45' },
  { pais: 'Dominica', codigo: '+1767' },
  { pais: 'Ecuador', codigo: '+593' },
  { pais: 'Egipto', codigo: '+20' },
  { pais: 'El Salvador', codigo: '+503' },
  { pais: 'Emiratos Arabes Unidos', codigo: '+971' },
  { pais: 'Eritrea', codigo: '+291' },
  { pais: 'Eslovaquia', codigo: '+421' },
  { pais: 'Eslovenia', codigo: '+386' },
  { pais: 'Espana', codigo: '+34' },
  { pais: 'Estados Unidos', codigo: '+1' },
  { pais: 'Estonia', codigo: '+372' },
  { pais: 'Esuatini', codigo: '+268' },
  { pais: 'Etiopia', codigo: '+251' },
  { pais: 'Filipinas', codigo: '+63' },
  { pais: 'Finlandia', codigo: '+358' },
  { pais: 'Fiyi', codigo: '+679' },
  { pais: 'Francia', codigo: '+33' },
  { pais: 'Gabon', codigo: '+241' },
  { pais: 'Gambia', codigo: '+220' },
  { pais: 'Georgia', codigo: '+995' },
  { pais: 'Ghana', codigo: '+233' },
  { pais: 'Granada', codigo: '+1473' },
  { pais: 'Grecia', codigo: '+30' },
  { pais: 'Guatemala', codigo: '+502' },
  { pais: 'Guinea', codigo: '+224' },
  { pais: 'Guinea Ecuatorial', codigo: '+240' },
  { pais: 'Guinea-Bisau', codigo: '+245' },
  { pais: 'Guyana', codigo: '+592' },
  { pais: 'Haiti', codigo: '+509' },
  { pais: 'Honduras', codigo: '+504' },
  { pais: 'Hungria', codigo: '+36' },
  { pais: 'India', codigo: '+91' },
  { pais: 'Indonesia', codigo: '+62' },
  { pais: 'Irak', codigo: '+964' },
  { pais: 'Iran', codigo: '+98' },
  { pais: 'Irlanda', codigo: '+353' },
  { pais: 'Islandia', codigo: '+354' },
  { pais: 'Islas Marshall', codigo: '+692' },
  { pais: 'Islas Salomon', codigo: '+677' },
  { pais: 'Israel', codigo: '+972' },
  { pais: 'Italia', codigo: '+39' },
  { pais: 'Jamaica', codigo: '+1876' },
  { pais: 'Japon', codigo: '+81' },
  { pais: 'Jordania', codigo: '+962' },
  { pais: 'Kazajistan', codigo: '+7' },
  { pais: 'Kenia', codigo: '+254' },
  { pais: 'Kirguistan', codigo: '+996' },
  { pais: 'Kiribati', codigo: '+686' },
  { pais: 'Kuwait', codigo: '+965' },
  { pais: 'Laos', codigo: '+856' },
  { pais: 'Lesoto', codigo: '+266' },
  { pais: 'Letonia', codigo: '+371' },
  { pais: 'Libano', codigo: '+961' },
  { pais: 'Liberia', codigo: '+231' },
  { pais: 'Libia', codigo: '+218' },
  { pais: 'Liechtenstein', codigo: '+423' },
  { pais: 'Lituania', codigo: '+370' },
  { pais: 'Luxemburgo', codigo: '+352' },
  { pais: 'Macedonia del Norte', codigo: '+389' },
  { pais: 'Madagascar', codigo: '+261' },
  { pais: 'Malasia', codigo: '+60' },
  { pais: 'Malaui', codigo: '+265' },
  { pais: 'Maldivas', codigo: '+960' },
  { pais: 'Mali', codigo: '+223' },
  { pais: 'Malta', codigo: '+356' },
  { pais: 'Marruecos', codigo: '+212' },
  { pais: 'Mauricio', codigo: '+230' },
  { pais: 'Mauritania', codigo: '+222' },
  { pais: 'Mexico', codigo: '+52' },
  { pais: 'Micronesia', codigo: '+691' },
  { pais: 'Moldavia', codigo: '+373' },
  { pais: 'Monaco', codigo: '+377' },
  { pais: 'Mongolia', codigo: '+976' },
  { pais: 'Montenegro', codigo: '+382' },
  { pais: 'Mozambique', codigo: '+258' },
  { pais: 'Namibia', codigo: '+264' },
  { pais: 'Nauru', codigo: '+674' },
  { pais: 'Nepal', codigo: '+977' },
  { pais: 'Nicaragua', codigo: '+505' },
  { pais: 'Niger', codigo: '+227' },
  { pais: 'Nigeria', codigo: '+234' },
  { pais: 'Noruega', codigo: '+47' },
  { pais: 'Nueva Zelanda', codigo: '+64' },
  { pais: 'Oman', codigo: '+968' },
  { pais: 'Paises Bajos', codigo: '+31' },
  { pais: 'Pakistan', codigo: '+92' },
  { pais: 'Palaos', codigo: '+680' },
  { pais: 'Panama', codigo: '+507' },
  { pais: 'Papua Nueva Guinea', codigo: '+675' },
  { pais: 'Paraguay', codigo: '+595' },
  { pais: 'Peru', codigo: '+51' },
  { pais: 'Polonia', codigo: '+48' },
  { pais: 'Portugal', codigo: '+351' },
  { pais: 'Reino Unido', codigo: '+44' },
  { pais: 'Republica Centroafricana', codigo: '+236' },
  { pais: 'Republica Checa', codigo: '+420' },
  { pais: 'Republica del Congo', codigo: '+242' },
  { pais: 'Republica Democratica del Congo', codigo: '+243' },
  { pais: 'Republica Dominicana', codigo: '+1809' },
  { pais: 'Ruanda', codigo: '+250' },
  { pais: 'Rumania', codigo: '+40' },
  { pais: 'Rusia', codigo: '+7' },
  { pais: 'Samoa', codigo: '+685' },
  { pais: 'San Cristobal y Nieves', codigo: '+1869' },
  { pais: 'San Marino', codigo: '+378' },
  { pais: 'San Vicente y las Granadinas', codigo: '+1784' },
  { pais: 'Santa Lucia', codigo: '+1758' },
  { pais: 'Santo Tome y Principe', codigo: '+239' },
  { pais: 'Senegal', codigo: '+221' },
  { pais: 'Serbia', codigo: '+381' },
  { pais: 'Seychelles', codigo: '+248' },
  { pais: 'Sierra Leona', codigo: '+232' },
  { pais: 'Singapur', codigo: '+65' },
  { pais: 'Siria', codigo: '+963' },
  { pais: 'Somalia', codigo: '+252' },
  { pais: 'Sri Lanka', codigo: '+94' },
  { pais: 'Sudafrica', codigo: '+27' },
  { pais: 'Sudan', codigo: '+249' },
  { pais: 'Sudan del Sur', codigo: '+211' },
  { pais: 'Suecia', codigo: '+46' },
  { pais: 'Suiza', codigo: '+41' },
  { pais: 'Surinam', codigo: '+597' },
  { pais: 'Tailandia', codigo: '+66' },
  { pais: 'Tanzania', codigo: '+255' },
  { pais: 'Tayikistan', codigo: '+992' },
  { pais: 'Timor Oriental', codigo: '+670' },
  { pais: 'Togo', codigo: '+228' },
  { pais: 'Tonga', codigo: '+676' },
  { pais: 'Trinidad y Tobago', codigo: '+1868' },
  { pais: 'Tunez', codigo: '+216' },
  { pais: 'Turkmenistan', codigo: '+993' },
  { pais: 'Turquia', codigo: '+90' },
  { pais: 'Tuvalu', codigo: '+688' },
  { pais: 'Ucrania', codigo: '+380' },
  { pais: 'Uganda', codigo: '+256' },
  { pais: 'Uruguay', codigo: '+598' },
  { pais: 'Uzbekistan', codigo: '+998' },
  { pais: 'Vanuatu', codigo: '+678' },
  { pais: 'Vaticano', codigo: '+379' },
  { pais: 'Venezuela', codigo: '+58' },
  { pais: 'Vietnam', codigo: '+84' },
  { pais: 'Yemen', codigo: '+967' },
  { pais: 'Yibuti', codigo: '+253' },
  { pais: 'Zambia', codigo: '+260' },
  { pais: 'Zimbabue', codigo: '+263' },
];
