export const MENSAJES = {
  OPERACION_EXITOSA: 'Operacion realizada correctamente',
  RECURSO_NO_ENCONTRADO: 'No se encontro el recurso solicitado',
  DATOS_DUPLICADOS: 'Ya existe un registro con esos datos',
  ERROR_SERVIDOR: 'Ocurrio un error inesperado',
  REGISTRO_ARCHIVADO: 'Registro archivado correctamente',
  REGISTRO_REACTIVADO: 'Registro reactivado correctamente',
  REGISTRO_ELIMINADO: 'Registro eliminado correctamente',
  ROL_CREADO: 'Rol creado correctamente',
  ROL_ACTUALIZADO: 'Rol actualizado correctamente',
  EMPLEADO_CREADO: 'Empleado creado correctamente',
  EMPLEADO_ACTUALIZADO: 'Empleado actualizado correctamente',
  USUARIO_CREADO: 'Usuario creado correctamente',
  USUARIO_ACTUALIZADO: 'Usuario actualizado correctamente',
  CLIENTE_CREADO: 'Cliente creado correctamente',
  CLIENTE_ACTUALIZADO: 'Cliente actualizado correctamente',
  PRODUCTO_CREADO: 'Producto creado correctamente',
  PRODUCTO_ACTUALIZADO: 'Producto actualizado correctamente',
} as const;
